# Generated by Django 5.1.7 on 2025-08-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subs',
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentMaker', to='authSystem.profile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='authSystem.profile')),
            ],
        ),
    ]
