# Generated by Django 5.1.7 on 2025-08-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0002_remove_profile_subs_subscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('creator', 'subscriber')},
        ),
    ]
