# Generated by Django 5.1.7 on 2025-08-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0003_alter_subscribe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=set(),
        ),
    ]
