# Generated by Django 5.1.7 on 2025-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0004_alter_subscribe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
