# Generated by Django 5.1.7 on 2025-08-12 15:24

import authSystem.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ava',
            field=models.ImageField(blank=True, default='ava/default.jpg', null=True, upload_to=authSystem.models.user_img_path),
        ),
    ]
