# Generated by Django 5.1.7 on 2025-08-12 15:25

import authSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0006_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava',
            field=models.ImageField(blank=True, default='ava/default.jpg', upload_to=authSystem.models.user_img_path),
        ),
    ]
