# Generated by Django 5.1.7 on 2025-08-12 15:27

import authSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0008_alter_profile_ava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava',
            field=models.ImageField(default='media/ava/default.jpg', upload_to=authSystem.models.user_img_path),
        ),
    ]
