# Generated by Django 5.1.7 on 2025-09-14 00:35

import django.db.models.deletion
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authSystem', '0002_alter_profile_ava'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=forum.models.get_forum_img)),
                ('confirmed', models.BooleanField(default=False)),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('time_upd', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='authSystem.profile')),
            ],
        ),
    ]
