# Generated by Django 5.1.7 on 2025-08-31 20:13

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postType', models.CharField(choices=[('video', 'video'), ('react', 'react'), ('img', 'img')], max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to=blog.models.get_user_video_path)),
                ('img', models.ImageField(blank=True, null=True, upload_to=blog.models.get_user_path)),
                ('react', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('draft', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('time_upd', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authSystem.profile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='blog.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('answerOnYourself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='blog.comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='authSystem.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.post')),
            ],
        ),
    ]
