# Generated by Django 5.1.7 on 2025-09-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
