# Generated by Django 5.1.7 on 2025-09-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0001_initial'),
        ('blog', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together={('author', 'fan')},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='authSystem.profile')),
            ],
        ),
    ]
