# Generated by Django 5.1.7 on 2025-09-12 12:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_rating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_user_cover),
        ),
    ]
