# Generated by Django 5.1.7 on 2025-09-10 23:11

import django.db.models.deletion
import panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authSystem', '0002_alter_profile_ava'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Some problems', max_length=100)),
                ('closed', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='authSystem.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Speak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speak', models.CharField(choices=[('answer', 'answer'), ('ask', 'ask')], max_length=100)),
                ('writes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=panel.models.message_img_path)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='panel.dialog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='authSystem.profile')),
            ],
        ),
    ]
